/*
 * This file is generated by jOOQ.
 */

import javax.annotation.processing.Generated;

/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>advisor</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.11"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Key {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AspectPropertiesRecord, Long> IDENTITY_ASPECT_PROPERTIES = Identities0.IDENTITY_ASPECT_PROPERTIES;
//    public static final Identity<MatrixFactsRecord, Long> IDENTITY_MATRIX_FACTS = Identities0.IDENTITY_MATRIX_FACTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ApplicationSettingsRecord> KEY_APPLICATION_SETTINGS_PRIMARY = UniqueKeys0.KEY_APPLICATION_SETTINGS_PRIMARY;
//    public static final UniqueKey<AspectPerformanceDataRecord> KEY_ASPECT_PERFORMANCE_DATA_PRIMARY = UniqueKeys0.KEY_ASPECT_PERFORMANCE_DATA_PRIMARY;
//    public static final UniqueKey<AspectPropertiesRecord> KEY_ASPECT_PROPERTIES_PRIMARY = UniqueKeys0.KEY_ASPECT_PROPERTIES_PRIMARY;
//    public static final UniqueKey<AspectsRecord> KEY_ASPECTS_PRIMARY = UniqueKeys0.KEY_ASPECTS_PRIMARY;
//    public static final UniqueKey<FactorPerformanceDataRecord> KEY_FACTOR_PERFORMANCE_DATA_PRIMARY = UniqueKeys0.KEY_FACTOR_PERFORMANCE_DATA_PRIMARY;
//    public static final UniqueKey<FactorsRecord> KEY_FACTORS_PRIMARY = UniqueKeys0.KEY_FACTORS_PRIMARY;
//    public static final UniqueKey<MatrixFactsRecord> KEY_MATRIX_FACTS_PRIMARY = UniqueKeys0.KEY_MATRIX_FACTS_PRIMARY;
//    public static final UniqueKey<ObjectivePerformanceDataRecord> KEY_OBJECTIVE_PERFORMANCE_DATA_PRIMARY = UniqueKeys0.KEY_OBJECTIVE_PERFORMANCE_DATA_PRIMARY;
//    public static final UniqueKey<TimeSeriesFactsRecord> KEY_TIME_SERIES_FACTS_PRIMARY = UniqueKeys0.KEY_TIME_SERIES_FACTS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

//    public static final ForeignKey<ApplicationSettingsRecord, ObjectiveLevelsRecord> APPLICATION_SETTINGS_IBFK_TOP_OBJECTIVE_LEVEL_FP = ForeignKeys0.APPLICATION_SETTINGS_IBFK_TOP_OBJECTIVE_LEVEL_FP;
//    public static final ForeignKey<AspectPerformanceDataRecord, AspectsRecord> ASPECT_PERFORMANCE_DATA_IBFK_ASPECT_ID = ForeignKeys0.ASPECT_PERFORMANCE_DATA_IBFK_ASPECT_ID;
//    public static final ForeignKey<AspectPropertiesRecord, AspectsRecord> ASPECT_PROPERTIES_IBFK_ASPECT_ID = ForeignKeys0.ASPECT_PROPERTIES_IBFK_ASPECT_ID;
//    public static final ForeignKey<FactorPerformanceDataRecord, FactorsRecord> FACTOR_PERFORMANCE_DATA_IBFK_FACTOR_ID = ForeignKeys0.FACTOR_PERFORMANCE_DATA_IBFK_FACTOR_ID;
//    public static final ForeignKey<FactorsRecord, AspectsRecord> FACTORS_IBFK_ASPECT_ID = ForeignKeys0.FACTORS_IBFK_ASPECT_ID;
//    public static final ForeignKey<MatrixFactsRecord, ObjectiveLevelsRecord> MATRIX_FACTS_IBFK_ANCESTOR_OBJECTIVE_LEVEL_FP = ForeignKeys0.MATRIX_FACTS_IBFK_ANCESTOR_OBJECTIVE_LEVEL_FP;
//    public static final ForeignKey<MatrixFactsRecord, ObjectiveLevelsRecord> MATRIX_FACTS_IBFK_DESCENDANT_OR_SELF_OBJECTIVE_LEVEL_FP = ForeignKeys0.MATRIX_FACTS_IBFK_DESCENDANT_OR_SELF_OBJECTIVE_LEVEL_FP;
//    public static final ForeignKey<ObjectivePerformanceDataRecord, FactorsRecord> OBJECTIVE_PERFORMANCE_DATA_IBFK_FACTOR_ID = ForeignKeys0.OBJECTIVE_PERFORMANCE_DATA_IBFK_FACTOR_ID;
//    public static final ForeignKey<ObjectivePerformanceDataRecord, ObjectiveLevelsRecord> OBJECTIVE_PERFORMANCE_DATA_IBFK_OBJECTIVE_LEVEL_FP = ForeignKeys0.OBJECTIVE_PERFORMANCE_DATA_IBFK_OBJECTIVE_LEVEL_FP;
//    public static final ForeignKey<TimeSeriesFactsRecord, FactorsRecord> TIME_SERIES_FACTS_IBFK_FACTOR_ID = ForeignKeys0.TIME_SERIES_FACTS_IBFK_FACTOR_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AspectPropertiesRecord, Long> IDENTITY_ASPECT_PROPERTIES = Internal.createIdentity(AspectProperties.ASPECT_PROPERTIES, AspectProperties.ASPECT_PROPERTIES.ID);
//        public static Identity<MatrixFactsRecord, Long> IDENTITY_MATRIX_FACTS = Internal.createIdentity(MatrixFacts.MATRIX_FACTS, MatrixFacts.MATRIX_FACTS.ID);
    }

//    private static class UniqueKeys0 {
//        public static final UniqueKey<ApplicationSettingsRecord> KEY_APPLICATION_SETTINGS_PRIMARY = Internal.createUniqueKey(ApplicationSettings.APPLICATION_SETTINGS, "KEY_application_settings_PRIMARY", ApplicationSettings.APPLICATION_SETTINGS.ID);
//        public static final UniqueKey<AspectPerformanceDataRecord> KEY_ASPECT_PERFORMANCE_DATA_PRIMARY = Internal.createUniqueKey(AspectPerformanceData.ASPECT_PERFORMANCE_DATA, "KEY_aspect_performance_data_PRIMARY", AspectPerformanceData.ASPECT_PERFORMANCE_DATA.ASPECT_ID, AspectPerformanceData.ASPECT_PERFORMANCE_DATA.CALENDAR_DATE);
//        public static final UniqueKey<AspectPropertiesRecord> KEY_ASPECT_PROPERTIES_PRIMARY = Internal.createUniqueKey(AspectProperties.ASPECT_PROPERTIES, "KEY_aspect_properties_PRIMARY", AspectProperties.ASPECT_PROPERTIES.ID);
//        public static final UniqueKey<AspectsRecord> KEY_ASPECTS_PRIMARY = Internal.createUniqueKey(Aspects.ASPECTS, "KEY_aspects_PRIMARY", Aspects.ASPECTS.ID);
//        public static final UniqueKey<FactorPerformanceDataRecord> KEY_FACTOR_PERFORMANCE_DATA_PRIMARY = Internal.createUniqueKey(FactorPerformanceData.FACTOR_PERFORMANCE_DATA, "KEY_factor_performance_data_PRIMARY", FactorPerformanceData.FACTOR_PERFORMANCE_DATA.FACTOR_ID, FactorPerformanceData.FACTOR_PERFORMANCE_DATA.CALENDAR_DATE);
//        public static final UniqueKey<FactorsRecord> KEY_FACTORS_PRIMARY = Internal.createUniqueKey(Factors.FACTORS, "KEY_factors_PRIMARY", Factors.FACTORS.ID);
//        public static final UniqueKey<MatrixFactsRecord> KEY_MATRIX_FACTS_PRIMARY = Internal.createUniqueKey(MatrixFacts.MATRIX_FACTS, "KEY_matrix_facts_PRIMARY", MatrixFacts.MATRIX_FACTS.ID);
//        public static final UniqueKey<ObjectivePerformanceDataRecord> KEY_OBJECTIVE_PERFORMANCE_DATA_PRIMARY = Internal.createUniqueKey(ObjectivePerformanceData.OBJECTIVE_PERFORMANCE_DATA, "KEY_objective_performance_data_PRIMARY", ObjectivePerformanceData.OBJECTIVE_PERFORMANCE_DATA.FACTOR_ID, ObjectivePerformanceData.OBJECTIVE_PERFORMANCE_DATA.OBJECTIVE_FP, ObjectivePerformanceData.OBJECTIVE_PERFORMANCE_DATA.CALENDAR_PERIOD_FP);
//        public static final UniqueKey<TimeSeriesFactsRecord> KEY_TIME_SERIES_FACTS_PRIMARY = Internal.createUniqueKey(TimeSeriesFacts.TIME_SERIES_FACTS, "KEY_time_series_facts_PRIMARY", TimeSeriesFacts.TIME_SERIES_FACTS.FACTOR_ID, TimeSeriesFacts.TIME_SERIES_FACTS.CALENDAR_PERIOD_FP);
//    }
//
//    private static class ForeignKeys0 {
//        public static final ForeignKey<ApplicationSettingsRecord, ObjectiveLevelsRecord> APPLICATION_SETTINGS_IBFK_TOP_OBJECTIVE_LEVEL_FP = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.plan.Keys.KEY_OBJECTIVE_LEVELS_PRIMARY, ApplicationSettings.APPLICATION_SETTINGS, "application_settings_ibfk_top_objective_level_fp", ApplicationSettings.APPLICATION_SETTINGS.TOP_OBJECTIVE_LEVEL_FP);
//        public static final ForeignKey<AspectPerformanceDataRecord, AspectsRecord> ASPECT_PERFORMANCE_DATA_IBFK_ASPECT_ID = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.advisor.Keys.KEY_ASPECTS_PRIMARY, AspectPerformanceData.ASPECT_PERFORMANCE_DATA, "aspect_performance_data_ibfk_aspect_id", AspectPerformanceData.ASPECT_PERFORMANCE_DATA.ASPECT_ID);
//        public static final ForeignKey<AspectPropertiesRecord, AspectsRecord> ASPECT_PROPERTIES_IBFK_ASPECT_ID = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.advisor.Keys.KEY_ASPECTS_PRIMARY, AspectProperties.ASPECT_PROPERTIES, "aspect_properties_ibfk_aspect_id", AspectProperties.ASPECT_PROPERTIES.ASPECT_ID);
//        public static final ForeignKey<FactorPerformanceDataRecord, FactorsRecord> FACTOR_PERFORMANCE_DATA_IBFK_FACTOR_ID = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.advisor.Keys.KEY_FACTORS_PRIMARY, FactorPerformanceData.FACTOR_PERFORMANCE_DATA, "factor_performance_data_ibfk_factor_id", FactorPerformanceData.FACTOR_PERFORMANCE_DATA.FACTOR_ID);
//        public static final ForeignKey<FactorsRecord, AspectsRecord> FACTORS_IBFK_ASPECT_ID = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.advisor.Keys.KEY_ASPECTS_PRIMARY, Factors.FACTORS, "factors_ibfk_aspect_id", Factors.FACTORS.ASPECT_ID);
//        public static final ForeignKey<MatrixFactsRecord, ObjectiveLevelsRecord> MATRIX_FACTS_IBFK_ANCESTOR_OBJECTIVE_LEVEL_FP = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.plan.Keys.KEY_OBJECTIVE_LEVELS_PRIMARY, MatrixFacts.MATRIX_FACTS, "matrix_facts_ibfk_ancestor_objective_level_fp", MatrixFacts.MATRIX_FACTS.ANCESTOR_OBJECTIVE_LEVEL_FP);
//        public static final ForeignKey<MatrixFactsRecord, ObjectiveLevelsRecord> MATRIX_FACTS_IBFK_DESCENDANT_OR_SELF_OBJECTIVE_LEVEL_FP = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.plan.Keys.KEY_OBJECTIVE_LEVELS_PRIMARY, MatrixFacts.MATRIX_FACTS, "matrix_facts_ibfk_descendant_or_self_objective_level_fp", MatrixFacts.MATRIX_FACTS.DESCENDANT_OR_SELF_OBJECTIVE_LEVEL_FP);
//        public static final ForeignKey<ObjectivePerformanceDataRecord, FactorsRecord> OBJECTIVE_PERFORMANCE_DATA_IBFK_FACTOR_ID = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.advisor.Keys.KEY_FACTORS_PRIMARY, ObjectivePerformanceData.OBJECTIVE_PERFORMANCE_DATA, "objective_performance_data_ibfk_factor_id", ObjectivePerformanceData.OBJECTIVE_PERFORMANCE_DATA.FACTOR_ID);
//        public static final ForeignKey<ObjectivePerformanceDataRecord, ObjectiveLevelsRecord> OBJECTIVE_PERFORMANCE_DATA_IBFK_OBJECTIVE_LEVEL_FP = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.plan.Keys.KEY_OBJECTIVE_LEVELS_PRIMARY, ObjectivePerformanceData.OBJECTIVE_PERFORMANCE_DATA, "objective_performance_data_ibfk_objective_level_fp", ObjectivePerformanceData.OBJECTIVE_PERFORMANCE_DATA.OBJECTIVE_LEVEL_FP);
//        public static final ForeignKey<TimeSeriesFactsRecord, FactorsRecord> TIME_SERIES_FACTS_IBFK_FACTOR_ID = Internal.createForeignKey(com.isolutions.inexus.advisor.graphql.database.jooqmodel.advisor.Keys.KEY_FACTORS_PRIMARY, TimeSeriesFacts.TIME_SERIES_FACTS, "time_series_facts_ibfk_factor_id", TimeSeriesFacts.TIME_SERIES_FACTS.FACTOR_ID);
//    }
}